{% set name = "dask-ml" %}
{% set version = "1.3.0" %}
{% set sha256 = "63dca0450431edca2d1d155d8f0b3bd57f13810fc42c2c0a888555b24ffa4b65" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
    - setuptools
    - setuptools_scm
  run:
    - dask >=1.0.0
    - dask-glm >=0.2.0
    - distributed >=1.25.0
    - multipledispatch >=0.4.9
    - numba
    - numpy
    - packaging
    - pandas >=0.23.0
    - python >=3
    - scikit-learn >=0.20.0
    - scipy
    - setuptools
    - six

test:
  imports:
    - dask_ml
    - dask_ml.cluster
    - dask_ml.decomposition
    - dask_ml.feature_extraction
    - dask_ml.linear_model
    - dask_ml.metrics
    - dask_ml.model_selection
    - dask_ml.preprocessing
    - dask_ml.utils
    - dask_ml.wrappers

about:
  home: http://github.com/dask/dask-ml
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Distributed and parallel machine learning using dask.
  description: |
    Distributed and parallel machine learning using dask.
  doc_url: https://ml.dask.org
  dev_url: https://github.com/dask/dask-ml

extra:
  recipe-maintainers:
    - TomAugspurger
    - jrbourbeau
